### ISSUE TITLE
[BUG]: Input.Acceleration Iphone not working

### ISSUE THREAD

**Issue by Deytooh** [naverz/zepeto-studio-kor#1012]
World Version : 1.5.1
Zepeto ver 3.14.2

**What features were you trying to implement?**
I need to use the accelerometer value.

**What problem did you encounter?**
The value is correctly returned for Android, but not for Iphone.

**Please tell us your development environment.**
Google Pixel 5 
Iphone 11

**Please attach the implemented code. If you have a screenshot, please attach it.**
console.log(Input.acceleration.toString());

**Comment by Zepeto-TechEvangelist** [comment]
Hello, Input.acceleration is actually the side-side movement of the device, and not the tilt. 
In order to get input working accurately the way it does in candy rolling, you should actually be utilizing **Input.gyro.attitude** to get the angle of rotation on the device. 
**Input.gyro.rotationRate** will give you the current rotation rate of the device, so if you rotate the device it will give you the delta rotation of the frame.

**Comment by Deytooh** [comment]
Hi, I wanted to use the side-side movement with Input.acceleration and not the gyro because the feeling is not the same.
I ended up using the **Input.gyro.gravity,** which its behaviour is the same as Input.acceleration but without being laggy, and more realistic. So I ended up applying some filters to it, it works nice 🔥  Thanks for the answer !

**Comment by Zepeto-TechEvangelist** [comment]
Cool! It would be great if you could share samples for other creators.
Thank you 😄
