### ISSUE TITLE
[BUG]: SerializedField slot becomes null

### ISSUE THREAD

**Issue by Cha-SeongHun** [naverz/zepeto-studio-kor#1299]
**Please tell us the version of the ZEPETO World package. (You can check the version in Unity > Window > Package Manager.)**
`1.8.0`

**Please tell us which version of the ZEPETO app is currently installed. (You can check the version in ZEPETO App > MY > Settings > Version.)**
`3.17.2`

**What features were you trying to implement?**
I want to fill the serialized object slot on inspector.

**What problem did you encounter?**
After filling the serializedField slot, the slot is filled with null when the focus is released from inspector.
This script is attached to the Prefab object.

**Please tell us your development environment.**
`Window 11` (Unity editor env)

**Please attach the implemented code. If you have a screenshot, please attach it.**
![Honeycam 2022-12-06 13-11-44](https://user-images.githubusercontent.com/100827088/205812454-96457056-4805-4561-81b0-91ad0a13e7c1.gif)

**Comment by Zepeto-TechEvangelist** [comment]
안녕하세요. 월드 버전 1.9.0에서 발견된 이슈라면 본문 수정 부탁드립니다. 제보 내용 확인해 보겠습니다.

**Comment by Zepeto-TechEvangelist** [comment]
Hello, As a result of testing the information reported, I would like to ask you to check whether you have dragged and placed an image file in the scene hierarchy rather than in the asset folder to the prefab inspector window.
In that case, the address value associated with the scene is stored, and when the scene is moved or restarted,
Since it is not in the scene, it is assumed that the problem is caused by missing the address value from the resource, and this is the same in general Unity.

For SlotImage, drag the Sprite resource image from the assets folder
After receiving a Transform called ItemSlot and applying it to the location, please check whether the same problem occurs.
